// 온도 구간별 옷차림 데이터 (8단계)
// 이미지 두 장 (한 장으로 마스터하자 기온별 옷차림 + 온도별 옷차림) 기준

export const CLOTHING_BANDS = [
  {
    id: 'summer-hot',
    range: '28°C 이상',
    minTemp: 28,
    maxTemp: 999,
    season: '여름',
    bgGradient: 'linear-gradient(135deg, #fffaf0 0%, #f9e7c8 100%)',
    accentColor: '#ff8a65',
    heroTitle: '덥다 더워! 최대한 시원하게',
    heroDesc: '한낮에는 땀이 줄줄. 민소매·반바지로 통풍 잘 되는 옷차림을 추천드려요.',
    tags: ['여름', '외출', '더위'],
    items: ['민소매', '반소매', '반바지', '원피스', '린넨바지', '샌들'],
    heroImage: 'images/hero-summer-hot.png',
    oneLineTip: '자외선 강해요. 선크림·모자·선글라스 챙기세요!',
  },
  {
    id: 'summer-mild',
    range: '23~27°C',
    minTemp: 23,
    maxTemp: 27,
    season: '여름',
    bgGradient: 'linear-gradient(135deg, #fff8ee 0%, #f8e5cb 100%)',
    accentColor: '#ffa726',
    heroTitle: '반소매가 딱 좋은 날씨',
    heroDesc: '활동하기 좋은 따뜻한 날씨예요. 반소매·얇은 셔츠로 가볍게 입어보세요.',
    tags: ['여름', '데일리', '캐주얼'],
    items: ['반소매', '얇은 셔츠', '반바지', '면바지', '스니커즈'],
    heroImage: 'images/hero-summer-mild.png',
    oneLineTip: '얇은 가디건 하나 챙기면 실내 냉방 대비 좋아요.',
  },
  {
    id: 'spring',
    range: '20~22°C',
    minTemp: 20,
    maxTemp: 22,
    season: '봄',
    bgGradient: 'linear-gradient(135deg, #fbf8ef 0%, #f2ead8 100%)',
    accentColor: '#b8a06a',
    heroTitle: '산책하기 딱 좋은 봄날',
    heroDesc: '포근한 봄 날씨예요. 블라우스·긴소매 티에 얇은 겉옷 하나면 충분해요.',
    tags: ['봄', '데일리', '산책'],
    items: ['블라우스', '긴소매 티', '면바지', '슬랙스', '얇은 가디건'],
    heroImage: 'images/hero-spring.png',
    oneLineTip: '일교차 있을 수 있어요. 얇은 가디건 챙기세요.',
  },
  {
    id: 'autumn-mild',
    range: '17~19°C',
    minTemp: 17,
    maxTemp: 19,
    season: '봄/가을',
    bgGradient: 'linear-gradient(135deg, #fbf4ea 0%, #f5dfc8 100%)',
    accentColor: '#e8a05a',
    heroTitle: '얇은 니트 꺼내입기 좋은 날',
    heroDesc: '선선한 환절기 날씨. 맨투맨이나 얇은 니트, 가디건으로 따뜻하게.',
    tags: ['가을', '환절기', '레이어드'],
    items: ['얇은 니트', '맨투맨', '후드티', '가디건', '긴 바지'],
    heroImage: 'images/hero-autumn-mild.png',
    oneLineTip: '아침, 저녁으로는 쌀쌀해요. 얇은 겉옷을 챙기세요!',
  },
  {
    id: 'autumn-cool',
    range: '12~16°C',
    minTemp: 12,
    maxTemp: 16,
    season: '봄/가을',
    bgGradient: 'linear-gradient(135deg, #fbf5ee 0%, #f3e4d5 100%)',
    accentColor: '#f6ad8f',
    heroTitle: '가벼운 외투로 따뜻하게!',
    heroDesc: '낮에는 포근하지만 아침, 저녁으로는 쌀쌀해요. 가벼운 외투를 추천드려요.',
    tags: ['봄/가을', '외출/데이트'],
    items: ['니트', '후드티', '가디건', '트렌치코트', '청바지', '스니커즈'],
    heroImage: 'images/hero-autumn-cool.png',
    oneLineTip: '얇은 외투 + 긴소매 조합이 딱 좋아요.',
  },
  {
    id: 'late-autumn',
    range: '9~11°C',
    minTemp: 9,
    maxTemp: 11,
    season: '늦가을',
    bgGradient: 'linear-gradient(135deg, #fbf3f2 0%, #f4dfe3 100%)',
    accentColor: '#e88aa0',
    heroTitle: '코트 꺼낼 시간이에요',
    heroDesc: '제법 쌀쌀한 날씨. 트렌치코트나 점퍼, 야상 같은 따뜻한 겉옷이 필요해요.',
    tags: ['늦가을', '쌀쌀'],
    items: ['트렌치코트', '야상', '점퍼', '니트', '기모바지', '부츠'],
    heroImage: 'images/hero-late-autumn.png',
    oneLineTip: '아침엔 두꺼운 외투, 낮엔 살짝 벗어도 돼요.',
  },
  {
    id: 'early-winter',
    range: '5~8°C',
    minTemp: 5,
    maxTemp: 8,
    season: '초겨울',
    bgGradient: 'linear-gradient(135deg, #f7f5fa 0%, #e8e2f0 100%)',
    accentColor: '#8d7ab5',
    heroTitle: '겨울이 성큼, 두툼하게',
    heroDesc: '꽤 추워요. 울 코트·가죽 자켓에 히트텍, 두꺼운 니트로 보온 신경 쓰세요.',
    tags: ['초겨울', '보온'],
    items: ['울 코트', '가죽 자켓', '히트텍', '두꺼운 니트', '레깅스', '부츠'],
    heroImage: 'images/hero-early-winter.png',
    oneLineTip: '바람 차가워요. 목도리까지 챙기면 완벽해요.',
  },
  {
    id: 'winter',
    range: '4°C 이하',
    minTemp: -999,
    maxTemp: 4,
    season: '겨울',
    bgGradient: 'linear-gradient(135deg, #f4f8fa 0%, #e2edf4 100%)',
    accentColor: '#6e95b5',
    heroTitle: '한파 주의! 꽁꽁 싸매세요',
    heroDesc: '매섭게 추운 날. 패딩·두꺼운 코트에 목도리, 장갑까지 풀세팅으로!',
    tags: ['한겨울', '한파'],
    items: ['패딩', '두꺼운 코트', '목도리', '장갑', '기모바지', '부츠'],
    heroImage: 'images/hero-winter.png',
    oneLineTip: '손끝·귀끝 동상 주의! 장갑·모자 꼭 챙기세요.',
  },
];

// 온도를 받아 해당 구간 반환
export function getBandByTemp(temp) {
  if (temp === null || temp === undefined || isNaN(temp)) return null;
  return CLOTHING_BANDS.find(b => temp >= b.minTemp && temp <= b.maxTemp);
}
